name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
    - uses: actions/checkout@v3
    - name: Check out ACE_TAO
      uses: actions/checkout@v3
      with:
        repository: DOCGroup/ACE_TAO
        path: ACE_TAO
    - name: Check out OpenDDS
      uses: actions/checkout@v3
      with:
        repository: OpenDDS/OpenDDS
        path: OpenDDS
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Test
      run: |
        export ACE_ROOT=`pwd`/ACE_TAO/ACE
        export DDS_ROOT=`pwd`/OpenDDS
        cd test
        npm ci
        ./basic_forward.pl
